backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Bộ sưu tập ảnh"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Tiêu đề"
        name: "title"
        widget: "string"
      - label: "Ảnh"
        name: "image"
        widget: "image"
      - label: "Mô tả"
        name: "body"
        widget: "markdown"
