backend:
  name: git-gateway
  branch: main  # Hoặc "master", tùy vào nhánh bạn sử dụng

media_folder: "static/uploads"  # Đảm bảo thư mục này tồn tại
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Đảm bảo thư mục này tồn tại
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
